#!/usr/bin/env php
<?php
/**
 * Created by PhpStorm.
 * User: kingzcheung
 * Date: 2016/10/5
 * Time: 22:27
 * @author  Kingz Cheung <kingzcheung@gmail.com>
 */

/**
 * 假如在 Public 目录下初始化第三方库（这里只是一个假设,事实上可以放在其他目录,只要下面的引入正确）
 * 引入 autoload 文件
 */
require_once __DIR__ . '/Public/vendor/autoload.php';

/**
 * 初始化应用目录,需要把当前目录作为参数
 */
$app = new Thinker\Application\App(__DIR__);

/**
 * 选择实例
 */
$app->runner();